<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-IIMQB4J" failures="0" tests="2" name="Default test" time="2.243" errors="0" timestamp="18 Mar 2022 07:48:27 GMT">
  <testcase classname="testcases.LoginTest" name="@BeforeMethod openApplication" time="0.0">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.debug(String)&amp;quot; because &amp;quot;this.log&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.debug(String)" because "this.log" is null
	at testcases.LoginTest.openApplication(LoginTest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase classname="testcases.LoginTest" name="@AfterMethod closure" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod closure -->
  <testcase classname="testcases.LoginTest" name="@BeforeMethod openApplication" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase classname="testcases.LoginTest" name="@AfterMethod closure" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod closure -->
  <testcase classname="testcases.LoginTest" name="login" time="0.002">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="testcases.LoginTest" name="login" time="0.001">
    <skipped/>
  </testcase> <!-- login -->
</testsuite> <!-- Default test -->
